DROP SCHEMA IF EXISTS server_db;
CREATE DATABASE server_db;
CREATE USER IF NOT EXISTS 'admin'@'localhost' IDENTIFIED BY 'admin';
GRANT ALL PRIVILEGES ON server_db.* TO 'admin'@'localhost';

USE server_db;

CREATE TABLE IF NOT EXISTS User(
    UserId INTEGER NOT NULL AUTO_INCREMENT,
    Name VARCHAR(124) NOT NULL,
    PRIMARY KEY (UserId)
);

CREATE TABLE IF NOT EXISTS Game(
    GameId INTEGER NOT NULL AUTO_INCREMENT,
    Name VARCHAR(124) NOT NULL,
    PRIMARY KEY (GameId)
);

CREATE TABLE IF NOT EXISTS Action(
    ActionId INTEGER NOT NULL AUTO_INCREMENT,
    UserId INTEGER,
    GameId INTEGER,
    Action VARCHAR(124) NOT NULL,
    PRIMARY KEY (ActionId),
    FOREIGN KEY (UserId) REFERENCES User(UserId),
    FOREIGN KEY (GameId) REFERENCES Game(GameId)
);